on:
  push:
    tags:
      - "v*"

name: Deploy Extension
jobs:
  deploy-vsx:
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo '${{ toJSON(github.ref) }}'

  deploy-marketplace:
    runs-on: ubuntu-latest
    steps:
      - run: echo '${{ toJSON(github.ref) }}'
